volumes:
  data:
  export:
services:
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pollos
      POSTGRES_PASSWORD: los_pollos
      POSTGRES_DB: Granja